[package]
name = "tetris"
version = "0.1.0"
authors = ["Andrei Jardan <jardan.andrei@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image","ttf"]

[dependencies.rand]
version = "0.8.1"
features = ["small_rng"]

[dependencies]
array2d = "0.2.1"
num = "0.3.1"
toml = "0.5"