# width = 1200
width = 700
height = 700
# borderless = false
block_size_draw = 32
block_size_tex = 16
block_path = "gfx/minecraft.png"
line_clear_path = "gfx/minecraft_line_clear_short.png"
line_clear_frames = 5

[[players]]
move_prepeat_duration = 0.15
move_repeat_duration = 0.05

[players.controls.keyboard]
left = "a"
right = "d"

rot_left = "q"
rot_right = "e"

softdrop = "s"
harddrop = "space"

store = "tab"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.keyboard]
left = "left"
right = "right"

rot_right_alt = "up"

softdrop_alt = "down"
harddrop = "right shift"

store = "return"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"
