width = 900
height = 900
# borderless = false
block_size = 30

[[players]]
move_prepeat_duration = 0.15
move_repeat_duration = 0.05

[players.controls.keyboard]
left = "a"
right = "d"

rot_left = "q"
rot_right = "e"

softdrop = "s"
harddrop = "space"

store = "tab"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.keyboard]
left = "left"
right = "right"

rot_right_alt = "up"

softdrop_alt = "down"
harddrop = "right shift"

store = "return"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"
