[[players]]
[players.controls.keyboard]
left = "a"
left_alt = "left"
right = "d"
right_alt = "right"

rot_left = "q"
rot_right = "e"
rot_right_alt = "up"

softdrop = "s"
softdrop_alt = "down"
harddrop = "space"

store = "w"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"

[[players]]
[players.controls.keyboard]
left = "h"
left_alt = "f12"
right = "k"
right_alt = "f12"

rot_left = "y"
rot_right = "i"
rot_right_alt = "f12"

softdrop = "j"
softdrop_alt = "f12"
harddrop = "n"

store = "u"

[players.controls.controller]
left = "dpleft"
right = "dpright"

rot_left = "leftshoulder"
rot_right = "rightshoulder"

softdrop = "dpdown"
harddrop = "a"

store = "righttrigger"